[package]
name = "micro_blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.3"
solana-program = "1.14.5"


[lib]
name = "micro_blog"
crate-type = ["cdylib", "lib"] 
